services:
  - type: static
    name: sharemelol
    plan: free
    buildCommand: |
      cd client && 
      npm install && 
      npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production
