services:
  - type: static
    name: sharemelol
    plan: free
    buildCommand: |
      cd client && 
      npm install --legacy-peer-deps && 
      npm run build
    staticPublishPath: ./client/build
